using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;

namespace Shared.Common.Models;

/// <summary>
/// Represents a standardized problem details response following RFC 7807.
/// </summary>
/// <remarks>
/// Excluded from code coverage: Model class for HTTP responses.
/// Response formatting is tested via integration tests.
/// </remarks>
[ExcludeFromCodeCoverage(Justification = "Model class for HTTP responses. Tested via integration tests.")]
public sealed class ProblemDetailsResponse
{
    /// <summary>
    /// Gets or sets a URI reference that identifies the problem type.
    /// </summary>
    [JsonPropertyName("type")]
    public string Type { get; init; } = "about:blank";

    /// <summary>
    /// Gets or sets a short, human-readable summary of the problem type.
    /// </summary>
    [JsonPropertyName("title")]
    public string Title { get; init; } = string.Empty;

    /// <summary>
    /// Gets or sets the HTTP status code generated by the origin server for this occurrence of the problem.
    /// </summary>
    [JsonPropertyName("status")]
    public int Status { get; init; }

    /// <summary>
    /// Gets or sets a human-readable explanation specific to this occurrence of the problem.
    /// </summary>
    [JsonPropertyName("detail")]
    public string? Detail { get; init; }

    /// <summary>
    /// Gets or sets a URI reference that identifies the specific occurrence of the problem.
    /// </summary>
    [JsonPropertyName("instance")]
    public string? Instance { get; init; }

    /// <summary>
    /// Gets or sets the trace identifier for correlation purposes.
    /// </summary>
    [JsonPropertyName("traceId")]
    public string? TraceId { get; init; }

    /// <summary>
    /// Gets or sets a dictionary containing validation errors, if any.
    /// </summary>
    [JsonPropertyName("errors")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Dictionary<string, string[]>? Errors { get; init; }

    /// <summary>
    /// Creates a problem details response with the specified parameters.
    /// </summary>
    /// <param name="status">The HTTP status code.</param>
    /// <param name="title">The problem title.</param>
    /// <param name="detail">Optional detailed message.</param>
    /// <param name="type">Optional problem type URI (defaults to "about:blank").</param>
    /// <param name="instance">Optional instance URI.</param>
    /// <param name="traceId">Optional trace identifier.</param>
    /// <returns>A new ProblemDetailsResponse instance.</returns>
    public static ProblemDetailsResponse Create(
        int status,
        string title,
        string? detail = null,
        string? type = null,
        string? instance = null,
        string? traceId = null)
    {
        return new ProblemDetailsResponse
        {
            Type = type ?? "about:blank",
            Title = title,
            Status = status,
            Detail = detail,
            Instance = instance,
            TraceId = traceId
        };
    }

    /// <summary>
    /// Creates a validation error problem details response.
    /// </summary>
    /// <param name="errors">Dictionary of validation errors keyed by field name.</param>
    /// <param name="traceId">Optional trace identifier.</param>
    /// <param name="instance">Optional instance URI.</param>
    /// <returns>A new ProblemDetailsResponse instance for validation errors.</returns>
    public static ProblemDetailsResponse CreateValidation(
        Dictionary<string, string[]> errors,
        string? traceId = null,
        string? instance = null)
    {
        return new ProblemDetailsResponse
        {
            Type = "https://tools.ietf.org/html/rfc7231#section-6.5.1",
            Title = "One or more validation errors occurred.",
            Status = 400,
            Detail = "Please refer to the errors property for additional details.",
            Instance = instance,
            TraceId = traceId,
            Errors = errors
        };
    }

    /// <summary>
    /// Creates a problem details response from an error code and message.
    /// </summary>
    /// <param name="errorCode">The error code.</param>
    /// <param name="errorMessage">The error message.</param>
    /// <param name="statusCode">The HTTP status code.</param>
    /// <param name="traceId">Optional trace identifier.</param>
    /// <param name="instance">Optional instance URI.</param>
    /// <returns>A new ProblemDetailsResponse instance.</returns>
    public static ProblemDetailsResponse CreateFromError(
        string errorCode,
        string errorMessage,
        int statusCode,
        string? traceId = null,
        string? instance = null)
    {
        var typeMap = new Dictionary<string, string>
        {
            { "Journey.NotFound", "https://tools.ietf.org/html/rfc7231#section-6.5.4" },
            { "Journey.Forbidden", "https://tools.ietf.org/html/rfc7231#section-6.5.3" },
            { "Journey.InvalidTransportType", "https://tools.ietf.org/html/rfc7231#section-6.5.1" },
            { "PublicLinkRevoked", "https://tools.ietf.org/html/rfc7231#section-6.5.10" }
        };

        var type = typeMap.TryGetValue(errorCode, out var t)
            ? t
            : "https://tools.ietf.org/html/rfc7231#section-6.6.1";

        return new ProblemDetailsResponse
        {
            Type = type,
            Title = GetTitleFromStatusCode(statusCode),
            Status = statusCode,
            Detail = errorMessage,
            Instance = instance,
            TraceId = traceId,
            Errors = new Dictionary<string, string[]>
            {
                { errorCode, new[] { errorMessage } }
            }
        };
    }

    private static string GetTitleFromStatusCode(int statusCode) => statusCode switch
    {
        400 => "Bad Request",
        401 => "Unauthorized",
        403 => "Forbidden",
        404 => "Not Found",
        409 => "Conflict",
        410 => "Gone",
        500 => "Internal Server Error",
        _ => "An error occurred"
    };
}
